import { useMemo, useState } from 'react'
import { CashIcon, ChartIcon, DownloadIcon, FilterIcon, SearchIcon, ChevronIcon, ReceiptIcon, QrIcon } from '../components/Icons'
import { formatDate, formatSoles, formatTime } from '../lib/format'
import type { Payment, PaymentStatus, SessionUser } from '../types'

interface DashboardPageProps { payments: Payment[]; user: SessionUser; variant?: 'dashboard' | 'operations' | 'reports'; onOpenPayment: (payment: Payment) => void }

const statusLabels: Record<PaymentStatus, string> = { PAID: 'Pagado', PENDING: 'Pendiente', FAILED: 'Fallido', EXPIRED: 'Vencido', CANCELLED: 'Cancelado' }

export function DashboardPage({ payments, user, variant = 'dashboard', onOpenPayment }: DashboardPageProps) {
  const [period, setPeriod] = useState('Hoy')
  const [status, setStatus] = useState<'ALL' | PaymentStatus>('ALL')
  const [method, setMethod] = useState<'ALL' | 'DIGITAL' | 'CASH'>('ALL')
  const [query, setQuery] = useState('')
  const paid = payments.filter((payment) => payment.status === 'PAID')
  const digitalTotal = paid.filter((payment) => payment.method === 'DIGITAL').reduce((total, payment) => total + payment.amountCents, 0)
  const cashTotal = paid.filter((payment) => payment.method === 'CASH').reduce((total, payment) => total + payment.amountCents, 0)
  const visiblePayments = useMemo(() => payments.filter((payment) => (status === 'ALL' || payment.status === status) && (method === 'ALL' || payment.method === method) && (!query || `${payment.reference} ${payment.createdBy}`.toLowerCase().includes(query.toLowerCase()))), [payments, status, method, query])
  const title = variant === 'operations' ? 'Operaciones' : variant === 'reports' ? 'Reportes' : 'Resumen del día'
  return <div className="page-stack dashboard-page">
    <div className="page-heading page-heading--dashboard"><div><div className="eyebrow">{variant === 'dashboard' ? 'VISTA GENERAL' : variant === 'reports' ? 'ANÁLISIS Y EXPORTACIÓN' : 'HISTORIAL DE COBROS'}</div><h1>{title}</h1><p>{variant === 'dashboard' ? 'Mira cómo va tu caja en tiempo real.' : variant === 'reports' ? 'Consulta y descarga el detalle de tus operaciones.' : 'Todas las operaciones registradas en tu punto de cobro.'}</p></div><div className="heading-actions"><div className="period-select"><span>Periodo</span><select value={period} onChange={(event) => setPeriod(event.target.value)}><option>Hoy</option><option>Esta semana</option><option>Este mes</option><option>Personalizado</option></select><ChevronIcon size={15} /></div>{variant === 'reports' && <button className="secondary-button"><DownloadIcon size={17} /> Exportar CSV</button>}</div></div>
    {variant === 'dashboard' && <div className="stats-grid"><div className="stat-card stat-card--primary"><div className="stat-card__head"><span>VENTAS HOY</span><span className="stat-icon"><ChartIcon size={18} /></span></div><strong>{formatSoles(digitalTotal + cashTotal)}</strong><div className="stat-card__foot"><span className="trend-up">↗ 12.5%</span><span>vs. ayer</span></div><div className="stat-card__sparkline"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="stat-card"><div className="stat-card__head"><span>COBROS DIGITALES</span><span className="stat-icon stat-icon--blue"><QrIcon size={18} /></span></div><strong>{formatSoles(digitalTotal)}</strong><div className="stat-card__foot"><span className="trend-up">↗ 8.2%</span><span>vs. ayer</span></div><div className="stat-progress"><span style={{ width: `${Math.min(100, Math.round((digitalTotal / Math.max(digitalTotal + cashTotal, 1)) * 100))}%` }} /></div><small>{Math.round((digitalTotal / Math.max(digitalTotal + cashTotal, 1)) * 100)}% del total</small></div><div className="stat-card"><div className="stat-card__head"><span>EFECTIVO</span><span className="stat-icon stat-icon--green"><CashIcon size={18} /></span></div><strong>{formatSoles(cashTotal)}</strong><div className="stat-card__foot"><span className="trend-up">↗ 18.1%</span><span>vs. ayer</span></div><div className="stat-progress stat-progress--green"><span style={{ width: `${Math.min(100, Math.round((cashTotal / Math.max(digitalTotal + cashTotal, 1)) * 100))}%` }} /></div><small>{Math.round((cashTotal / Math.max(digitalTotal + cashTotal, 1)) * 100)}% del total</small></div><div className="stat-card"><div className="stat-card__head"><span>OPERACIONES</span><span className="stat-icon stat-icon--violet"><ReceiptIcon size={18} /></span></div><strong>{payments.length}</strong><div className="stat-card__foot"><span className="trend-up">↗ 6.4%</span><span>vs. ayer</span></div><div className="stat-mini-metrics"><span><b>{payments.filter((item) => item.status === 'PENDING').length}</b> pendientes</span><span><b>{payments.filter((item) => item.status === 'PAID').length}</b> pagadas</span></div></div></div>}
    <section className="panel transactions-panel"><div className="transactions-head"><div><h2>{variant === 'reports' ? 'Resumen de operaciones' : 'Últimas operaciones'}</h2><p>{visiblePayments.length} operaciones encontradas</p></div><div className="transaction-filters"><div className="search-input"><SearchIcon size={16} /><input placeholder="Buscar referencia o cajero" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="filter-select"><FilterIcon size={15} /><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="ALL">Todos los estados</option><option value="PAID">Pagados</option><option value="PENDING">Pendientes</option><option value="FAILED">Fallidos</option></select></div><div className="filter-select filter-select--method"><select value={method} onChange={(event) => setMethod(event.target.value as typeof method)}><option value="ALL">Todos los métodos</option><option value="DIGITAL">Digital</option><option value="CASH">Efectivo</option></select></div></div></div><div className="table-wrap"><table><thead><tr><th>OPERACIÓN</th><th>FECHA Y HORA</th><th>MÉTODO</th><th>CAJERO</th><th>MONTO</th><th>ESTADO</th><th /></tr></thead><tbody>{visiblePayments.map((payment) => <tr key={payment.id} onClick={() => payment.status === 'PENDING' && onOpenPayment(payment)}><td><span className="reference-cell"><span className={`reference-icon ${payment.method === 'CASH' ? 'reference-icon--cash' : ''}`}>{payment.method === 'CASH' ? <CashIcon size={15} /> : <QrIcon size={15} />}</span><span><strong>{payment.reference}</strong><small>{payment.provider === 'cash' ? 'Registro en caja' : 'QR dinámico'}</small></span></span></td><td><span className="date-cell">{formatDate(payment.createdAt)}</span></td><td><span className={`method-tag ${payment.method === 'CASH' ? 'method-tag--cash' : ''}`}><i />{payment.method === 'CASH' ? 'Efectivo' : 'Digital'}</span></td><td><span className="cashier-cell"><span className="avatar avatar--tiny">{payment.createdBy.split(' ').map((item) => item[0]).join('').slice(0, 2)}</span>{payment.createdBy}</span></td><td><strong className="amount-cell">{formatSoles(payment.amountCents)}</strong></td><td><span className={`status-tag status-tag--${payment.status.toLowerCase()}`}><i />{statusLabels[payment.status]}</span></td><td><button className="row-menu" aria-label="Ver detalle">•••</button></td></tr>)}</tbody></table>{visiblePayments.length === 0 && <div className="empty-state"><ReceiptIcon size={26} /><strong>No hay operaciones con estos filtros</strong><small>Prueba ajustando tu búsqueda o filtros.</small></div>}</div><div className="table-footer"><span>Mostrando <strong>{visiblePayments.length}</strong> de <strong>{payments.length}</strong> operaciones</span><div className="pagination"><button disabled>‹</button><button className="pagination--active">1</button><button disabled>›</button></div></div></section>
    {variant === 'dashboard' && <div className="dashboard-bottom-grid"><section className="panel weekly-panel"><div className="panel-heading-row"><div><h2>Rendimiento semanal</h2><p>Ingresos de los últimos 7 días</p></div><span className="chart-legend"><i /> Ventas</span></div><div className="bar-chart"><div className="bar-chart__y"><span>S/ 2k</span><span>S/ 1k</span><span>S/ 0</span></div><div className="bar-chart__bars">{['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'].map((day, index) => <div className="bar-column" key={day}><span className={`bar ${index === 5 ? 'bar--today' : ''}`} style={{ height: `${[42, 58, 38, 72, 53, 88, 67][index]}%` }} /><small>{day}</small></div>)}</div></div></section><section className="panel quick-help"><div className="quick-help__icon">✦</div><h2>Todo bajo control</h2><p>Tu caja está operando con normalidad. Sigue creando cobros rápidos para tus clientes.</p><button className="text-button">Ver guía rápida <span>↗</span></button></section></div>}
  </div>
}
