import { useState } from 'react'
import { ArrowIcon, CheckIcon, ClockIcon, InfoIcon, QrIcon } from '../components/Icons'
import { QrCode } from '../components/QrCode'
import { formatSoles } from '../lib/format'
import { simulateMockPayment } from '../lib/demoStore'
import type { Payment } from '../types'

interface MockSimulatorPageProps { payment: Payment; onComplete: (payment: Payment) => void; onBack: () => void }

export function MockSimulatorPage({ payment, onComplete, onBack }: MockSimulatorPageProps) {
  const [busy, setBusy] = useState(false)
  const [done, setDone] = useState(false)
  async function handlePay() { if (busy) return; setBusy(true); const updated = await simulateMockPayment(payment); setDone(true); setBusy(false); window.setTimeout(() => onComplete(updated), 1000) }
  return <div className="simulator-shell"><div className="simulator-top"><button className="back-link" onClick={onBack}>← Volver al cobro</button><span className="simulator-env"><span /> Entorno de desarrollo</span></div><div className="simulator-wrap"><div className="simulator-header"><div className="simulator-header__icon"><QrIcon size={22} /></div><div><div className="eyebrow">MOCK PAYMENT PROVIDER</div><h1>Simulador de pago</h1><p>Prueba el flujo completo sin realizar un cargo real.</p></div></div><section className="simulator-card-main"><div className="simulator-card-main__left"><div className="simulator-qr-label">Escanea este código <span>•</span> Demo</div><QrCode value={payment.reference} size="large" /><div className="simulator-phone-hint"><QrIcon size={16} /> Simulación de billetera digital</div></div><div className="simulator-card-main__right"><div className="simulator-operation-label">DETALLE DE OPERACIÓN</div><div className="simulator-operation-amount">{formatSoles(payment.amountCents)}</div><div className="simulator-detail-row"><span>Referencia</span><strong>{payment.reference}</strong></div><div className="simulator-detail-row"><span>Estado actual</span><span className="status-tag status-tag--pending"><i /> Pendiente</span></div><div className="simulator-detail-row"><span>Proveedor</span><strong>MockPaymentProvider</strong></div><div className="simulator-rule" /><div className="simulator-warning"><InfoIcon size={17} /><p>Este botón enviará un evento al webhook interno, igual que un proveedor real. La operación se validará antes de marcarse como pagada.</p></div><button className={`primary-button primary-button--large simulator-pay-button ${done ? 'simulator-pay-button--done' : ''}`} onClick={handlePay} disabled={busy || done}>{done ? <><CheckIcon size={20} /> Pago enviado</> : busy ? 'Enviando evento…' : <>Simular pago exitoso <ArrowIcon size={18} /></>}</button><button className="ghost-button" onClick={onBack}>Cancelar</button></div></section><div className="simulator-flow"><div className="simulator-flow__title">FLUJO DE VALIDACIÓN</div><div className="flow-steps"><div className="flow-step flow-step--done"><span><CheckIcon size={14} /></span><p><strong>Evento creado</strong><small>Mock webhook</small></p></div><i /><div className="flow-step"><span>2</span><p><strong>Validar operación</strong><small>Referencia + monto</small></p></div><i /><div className="flow-step"><span>3</span><p><strong>Confirmar pago</strong><small>Estado PAID</small></p></div></div></div><div className="simulator-footer"><ClockIcon size={14} /> Las operaciones de prueba no mueven dinero real y están deshabilitadas en producción.</div></div></div>
}
